### ISSUE TITLE
VS2017 LESS Compiler fails with { [Error: Cannot find module 'promise'] code: 'MODULE_NOT_FOUND' }

### ISSUE THREAD

**Issue by JoyalToTheWorld** [madskristensen/LessCompiler#1]
### Installed product versions
- Visual Studio: 2017 Enterprise

### Steps to recreate
1. Install LESS Compiler extension
2. Create .less file
3. Make change and save .less file
4. Observe output window for LESS Compiler

### Current behavior
{ [Error: Cannot find module 'promise'] code: 'MODULE_NOT_FOUND' }

### Expected behavior
LESS File should be compiled and output successfully generated or an actionable error message should be displayed

**Comment by nourben** [comment]
Hi, how did you resolve the problem ?
