### ISSUE TITLE
"Compare with Unmodified" using GIT on .less file will cause VS 2017 to crash

### ISSUE THREAD

**Issue by PetrOndrusek** [madskristensen/LessCompiler#14]
### Installed product versions
- Visual Studio: 2017 Professional 15.9.7
- This extension: 0.9.44

### Description
I am using GIT as a source control system and I also use LESS Compiler extension (and I like it :-) ). But when I modify some .less file and go to Team Explorer, stand on it, click right mouse button and select "Compare with Unmodified", after a while Visual Studio crashes... Maybe LESS Compiler is not fully compatible with GIT subsystem.

### Steps to recreate
1. Use GIT as a source control system
2. Modify some .less file
3. Go to Team Explorer
4. Select the .less file
5. Right click on the file
6. Select "Compare with Unmodified"

### Current behavior
Visual Studio freezes for a while and then crashes.

### Expected behavior
Stop the crashing.

**Comment by viktooli** [comment]
Crash also happens using TFS for source control.
